javac ./annexe/Annexe.java
javac ./info/Critere.java
javac ./info/Information.java
javac ./user/User.java
javac ./CheckLogin.java
javac ./CheckSession.java
javac ./InsertCritere.java
javac ./InsertInfo.java
javac ./Liste.java
javac ./Deconnexion.java
javac ./Inscription.java
javac ./ListCritere.java
javac ./formulaire/Formulaire.java