javac ./annexe/Annexe.java
javac ./info/Critere.java
javac ./info/Information.java
javac ./user/User.java
javac ./match/Match.java
javac ./raikitra/Raikitra.java
javac ./formulaire/Formulaire.java
javac ./CheckLogin.java
javac ./CheckSession.java
javac ./InsertCritere.java
javac ./InsertInfo.java
javac ./Liste.java
javac ./Deconnexion.java
javac ./Inscription.java
javac ./ListCritere.java
javac ./InsertMatch.java
javac ./ListMatch.java
javac ./InsertRaikitra.java
javac ./raikitra/Indisponible.java
javac ./InsertIndisponible.java
javac ./note/Note.java